# Generated by Django 4.0.2 on 2022-03-22 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_quiz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizes'},
        ),
    ]
